# Generated by Django 4.2.30 on 2026-06-07 14:50

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChatbotRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('question', models.TextField()),
                ('answer', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Chatbot Record',
                'verbose_name_plural': 'Chatbot Records',
                'db_table': 'chatbot_record',
                'ordering': ['-created_at'],
            },
        ),
    ]
